# Generated by Django 2.2 on 2019-04-14 10:31

import commonvoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording',
            field=models.FileField(upload_to=commonvoice.models.upload_to),
        ),
    ]
