# Generated by Django 2.2 on 2019-04-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonvoice', '0003_auto_20190420_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='verify_count',
            new_name='correct_count',
        ),
    ]
