# Generated by Django 2.2 on 2019-04-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonvoice', '0005_recording_wrong_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='wrong_count',
            new_name='incorrect_count',
        ),
    ]
